name: Publish to PyPI

on:
  release:
    types: [published]  # Trigger the workflow when a release is published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Extract version from tag
      id: get_version
      run: |
        echo "PACKAGE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Display the package version
      run: |
        echo "Release Version: ${{ env.PACKAGE_VERSION }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel build twine

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m twine upload dist/* --non-interactive --skip-existing